export const SUPPORTED_CURRENCIES = [
  { code: 'AED', name: 'United Arab Emirates Dirham (AED)', symbol: 'AED' },
  { code: 'AFN', name: 'Afghan Afghani (AFN)', symbol: 'AFN' },
  { code: 'ALL', name: 'Albanian Lek (ALL)', symbol: 'ALL' },
  { code: 'AMD', name: 'Armenian Dram (AMD)', symbol: 'AMD' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder (ANG)', symbol: 'ANG' },
  { code: 'AOA', name: 'Angolan Kwanza (AOA)', symbol: 'AOA' },
  { code: 'ARS', name: 'Argentine Peso (ARS)', symbol: 'ARS' },
  { code: 'AUD', name: 'Australian Dollar (A$)', symbol: 'A$' },
  { code: 'AWG', name: 'Aruban Florin (AWG)', symbol: 'AWG' },
  { code: 'AZN', name: 'Azerbaijani Manat (AZN)', symbol: 'AZN' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark (BAM)', symbol: 'BAM' },
  { code: 'BBD', name: 'Barbadian Dollar (BBD)', symbol: 'BBD' },
  { code: 'BDT', name: 'Bangladeshi Taka (BDT)', symbol: 'BDT' },
  { code: 'BGN', name: 'Bulgarian Lev (BGN)', symbol: 'BGN' },
  { code: 'BHD', name: 'Bahraini Dinar (BHD)', symbol: 'BHD' },
  { code: 'BIF', name: 'Burundian Franc (BIF)', symbol: 'BIF' },
  { code: 'BMD', name: 'Bermudan Dollar (BMD)', symbol: 'BMD' },
  { code: 'BND', name: 'Brunei Dollar (BND)', symbol: 'BND' },
  { code: 'BOB', name: 'Bolivian Boliviano (BOB)', symbol: 'BOB' },
  { code: 'BRL', name: 'Brazilian Real (R$)', symbol: 'R$' },
  { code: 'BSD', name: 'Bahamian Dollar (BSD)', symbol: 'BSD' },
  { code: 'BTN', name: 'Bhutanese Ngultrum (BTN)', symbol: 'BTN' },
  { code: 'BWP', name: 'Botswanan Pula (BWP)', symbol: 'BWP' },
  { code: 'BYN', name: 'Belarusian Ruble (BYN)', symbol: 'BYN' },
  { code: 'BZD', name: 'Belize Dollar (BZD)', symbol: 'BZD' },
  { code: 'CAD', name: 'Canadian Dollar (CA$)', symbol: 'CA$' },
  { code: 'CDF', name: 'Congolese Franc (CDF)', symbol: 'CDF' },
  { code: 'CHF', name: 'Swiss Franc (CHF)', symbol: 'CHF' },
  { code: 'CLF', name: 'Chilean Unit of Account (UF) (CLF)', symbol: 'CLF' },
  { code: 'CLP', name: 'Chilean Peso (CLP)', symbol: 'CLP' },
  { code: 'CNH', name: 'Chinese Yuan (offshore) (CNH)', symbol: 'CNH' },
  { code: 'CNY', name: 'Chinese Yuan (CN¥)', symbol: 'CN¥' },
  { code: 'COP', name: 'Colombian Peso (COP)', symbol: 'COP' },
  { code: 'CRC', name: 'Costa Rican Colón (CRC)', symbol: 'CRC' },
  { code: 'CUP', name: 'Cuban Peso (CUP)', symbol: 'CUP' },
  { code: 'CVE', name: 'Cape Verdean Escudo (CVE)', symbol: 'CVE' },
  { code: 'CZK', name: 'Czech Koruna (CZK)', symbol: 'CZK' },
  { code: 'DJF', name: 'Djiboutian Franc (DJF)', symbol: 'DJF' },
  { code: 'DKK', name: 'Danish Krone (DKK)', symbol: 'DKK' },
  { code: 'DOP', name: 'Dominican Peso (DOP)', symbol: 'DOP' },
  { code: 'DZD', name: 'Algerian Dinar (DZD)', symbol: 'DZD' },
  { code: 'EGP', name: 'Egyptian Pound (EGP)', symbol: 'EGP' },
  { code: 'ERN', name: 'Eritrean Nakfa (ERN)', symbol: 'ERN' },
  { code: 'ETB', name: 'Ethiopian Birr (ETB)', symbol: 'ETB' },
  { code: 'EUR', name: 'Euro (€)', symbol: '€' },
  { code: 'FJD', name: 'Fijian Dollar (FJD)', symbol: 'FJD' },
  { code: 'FKP', name: 'Falkland Islands Pound (FKP)', symbol: 'FKP' },
  { code: 'FOK', name: 'FOK (FOK)', symbol: 'FOK' },
  { code: 'GBP', name: 'British Pound (£)', symbol: '£' },
  { code: 'GEL', name: 'Georgian Lari (GEL)', symbol: 'GEL' },
  { code: 'GGP', name: 'GGP (GGP)', symbol: 'GGP' },
  { code: 'GHS', name: 'Ghanaian Cedi (GHS)', symbol: 'GHS' },
  { code: 'GIP', name: 'Gibraltar Pound (GIP)', symbol: 'GIP' },
  { code: 'GMD', name: 'Gambian Dalasi (GMD)', symbol: 'GMD' },
  { code: 'GNF', name: 'Guinean Franc (GNF)', symbol: 'GNF' },
  { code: 'GTQ', name: 'Guatemalan Quetzal (GTQ)', symbol: 'GTQ' },
  { code: 'GYD', name: 'Guyanaese Dollar (GYD)', symbol: 'GYD' },
  { code: 'HKD', name: 'Hong Kong Dollar (HK$)', symbol: 'HK$' },
  { code: 'HNL', name: 'Honduran Lempira (HNL)', symbol: 'HNL' },
  { code: 'HRK', name: 'Croatian Kuna (HRK)', symbol: 'HRK' },
  { code: 'HTG', name: 'Haitian Gourde (HTG)', symbol: 'HTG' },
  { code: 'HUF', name: 'Hungarian Forint (HUF)', symbol: 'HUF' },
  { code: 'IDR', name: 'Indonesian Rupiah (IDR)', symbol: 'IDR' },
  { code: 'ILS', name: 'Israeli New Shekel (₪)', symbol: '₪' },
  { code: 'IMP', name: 'IMP (IMP)', symbol: 'IMP' },
  { code: 'INR', name: 'Indian Rupee (₹)', symbol: '₹' },
  { code: 'IQD', name: 'Iraqi Dinar (IQD)', symbol: 'IQD' },
  { code: 'IRR', name: 'Iranian Rial (IRR)', symbol: 'IRR' },
  { code: 'ISK', name: 'Icelandic Króna (ISK)', symbol: 'ISK' },
  { code: 'JEP', name: 'JEP (JEP)', symbol: 'JEP' },
  { code: 'JMD', name: 'Jamaican Dollar (JMD)', symbol: 'JMD' },
  { code: 'JOD', name: 'Jordanian Dinar (JOD)', symbol: 'JOD' },
  { code: 'JPY', name: 'Japanese Yen (¥)', symbol: '¥' },
  { code: 'KES', name: 'Kenyan Shilling (KES)', symbol: 'KES' },
  { code: 'KGS', name: 'Kyrgystani Som (KGS)', symbol: 'KGS' },
  { code: 'KHR', name: 'Cambodian Riel (KHR)', symbol: 'KHR' },
  { code: 'KID', name: 'KID (KID)', symbol: 'KID' },
  { code: 'KMF', name: 'Comorian Franc (KMF)', symbol: 'KMF' },
  { code: 'KRW', name: 'South Korean Won (₩)', symbol: '₩' },
  { code: 'KWD', name: 'Kuwaiti Dinar (KWD)', symbol: 'KWD' },
  { code: 'KYD', name: 'Cayman Islands Dollar (KYD)', symbol: 'KYD' },
  { code: 'KZT', name: 'Kazakhstani Tenge (KZT)', symbol: 'KZT' },
  { code: 'LAK', name: 'Laotian Kip (LAK)', symbol: 'LAK' },
  { code: 'LBP', name: 'Lebanese Pound (LBP)', symbol: 'LBP' },
  { code: 'LKR', name: 'Sri Lankan Rupee (LKR)', symbol: 'LKR' },
  { code: 'LRD', name: 'Liberian Dollar (LRD)', symbol: 'LRD' },
  { code: 'LSL', name: 'Lesotho Loti (LSL)', symbol: 'LSL' },
  { code: 'LYD', name: 'Libyan Dinar (LYD)', symbol: 'LYD' },
  { code: 'MAD', name: 'Moroccan Dirham (MAD)', symbol: 'MAD' },
  { code: 'MDL', name: 'Moldovan Leu (MDL)', symbol: 'MDL' },
  { code: 'MGA', name: 'Malagasy Ariary (MGA)', symbol: 'MGA' },
  { code: 'MKD', name: 'Macedonian Denar (MKD)', symbol: 'MKD' },
  { code: 'MMK', name: 'Myanmar Kyat (MMK)', symbol: 'MMK' },
  { code: 'MNT', name: 'Mongolian Tugrik (MNT)', symbol: 'MNT' },
  { code: 'MOP', name: 'Macanese Pataca (MOP)', symbol: 'MOP' },
  { code: 'MRU', name: 'Mauritanian Ouguiya (MRU)', symbol: 'MRU' },
  { code: 'MUR', name: 'Mauritian Rupee (MUR)', symbol: 'MUR' },
  { code: 'MVR', name: 'Maldivian Rufiyaa (MVR)', symbol: 'MVR' },
  { code: 'MWK', name: 'Malawian Kwacha (MWK)', symbol: 'MWK' },
  { code: 'MXN', name: 'Mexican Peso (MX$)', symbol: 'MX$' },
  { code: 'MYR', name: 'Malaysian Ringgit (MYR)', symbol: 'MYR' },
  { code: 'MZN', name: 'Mozambican Metical (MZN)', symbol: 'MZN' },
  { code: 'NAD', name: 'Namibian Dollar (NAD)', symbol: 'NAD' },
  { code: 'NGN', name: 'Nigerian Naira (NGN)', symbol: 'NGN' },
  { code: 'NIO', name: 'Nicaraguan Córdoba (NIO)', symbol: 'NIO' },
  { code: 'NOK', name: 'Norwegian Krone (NOK)', symbol: 'NOK' },
  { code: 'NPR', name: 'Nepalese Rupee (NPR)', symbol: 'NPR' },
  { code: 'NZD', name: 'New Zealand Dollar (NZ$)', symbol: 'NZ$' },
  { code: 'OMR', name: 'Omani Rial (OMR)', symbol: 'OMR' },
  { code: 'PAB', name: 'Panamanian Balboa (PAB)', symbol: 'PAB' },
  { code: 'PEN', name: 'Peruvian Sol (PEN)', symbol: 'PEN' },
  { code: 'PGK', name: 'Papua New Guinean Kina (PGK)', symbol: 'PGK' },
  { code: 'PHP', name: 'Philippine Peso (₱)', symbol: '₱' },
  { code: 'PKR', name: 'Pakistani Rupee (PKR)', symbol: 'PKR' },
  { code: 'PLN', name: 'Polish Zloty (PLN)', symbol: 'PLN' },
  { code: 'PYG', name: 'Paraguayan Guarani (PYG)', symbol: 'PYG' },
  { code: 'QAR', name: 'Qatari Riyal (QAR)', symbol: 'QAR' },
  { code: 'RON', name: 'Romanian Leu (RON)', symbol: 'RON' },
  { code: 'RSD', name: 'Serbian Dinar (RSD)', symbol: 'RSD' },
  { code: 'RUB', name: 'Russian Ruble (RUB)', symbol: 'RUB' },
  { code: 'RWF', name: 'Rwandan Franc (RWF)', symbol: 'RWF' },
  { code: 'SAR', name: 'Saudi Riyal (SAR)', symbol: 'SAR' },
  { code: 'SBD', name: 'Solomon Islands Dollar (SBD)', symbol: 'SBD' },
  { code: 'SCR', name: 'Seychellois Rupee (SCR)', symbol: 'SCR' },
  { code: 'SDG', name: 'Sudanese Pound (SDG)', symbol: 'SDG' },
  { code: 'SEK', name: 'Swedish Krona (SEK)', symbol: 'SEK' },
  { code: 'SGD', name: 'Singapore Dollar (SGD)', symbol: 'SGD' },
  { code: 'SHP', name: 'St. Helena Pound (SHP)', symbol: 'SHP' },
  { code: 'SLE', name: 'Sierra Leonean Leone (SLE)', symbol: 'SLE' },
  { code: 'SLL', name: 'Sierra Leonean Leone (1964—2022) (SLL)', symbol: 'SLL' },
  { code: 'SOS', name: 'Somali Shilling (SOS)', symbol: 'SOS' },
  { code: 'SRD', name: 'Surinamese Dollar (SRD)', symbol: 'SRD' },
  { code: 'SSP', name: 'South Sudanese Pound (SSP)', symbol: 'SSP' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra (STN)', symbol: 'STN' },
  { code: 'SYP', name: 'Syrian Pound (SYP)', symbol: 'SYP' },
  { code: 'SZL', name: 'Swazi Lilangeni (SZL)', symbol: 'SZL' },
  { code: 'THB', name: 'Thai Baht (THB)', symbol: 'THB' },
  { code: 'TJS', name: 'Tajikistani Somoni (TJS)', symbol: 'TJS' },
  { code: 'TMT', name: 'Turkmenistani Manat (TMT)', symbol: 'TMT' },
  { code: 'TND', name: 'Tunisian Dinar (TND)', symbol: 'TND' },
  { code: 'TOP', name: 'Tongan Paʻanga (TOP)', symbol: 'TOP' },
  { code: 'TRY', name: 'Turkish Lira (TRY)', symbol: 'TRY' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar (TTD)', symbol: 'TTD' },
  { code: 'TVD', name: 'TVD (TVD)', symbol: 'TVD' },
  { code: 'TWD', name: 'New Taiwan Dollar (NT$)', symbol: 'NT$' },
  { code: 'TZS', name: 'Tanzanian Shilling (TZS)', symbol: 'TZS' },
  { code: 'UAH', name: 'Ukrainian Hryvnia (UAH)', symbol: 'UAH' },
  { code: 'UGX', name: 'Ugandan Shilling (UGX)', symbol: 'UGX' },
  { code: 'USD', name: 'US Dollar ($)', symbol: '$' },
  { code: 'UYU', name: 'Uruguayan Peso (UYU)', symbol: 'UYU' },
  { code: 'UZS', name: 'Uzbekistani Som (UZS)', symbol: 'UZS' },
  { code: 'VES', name: 'Venezuelan Bolívar (VES)', symbol: 'VES' },
  { code: 'VND', name: 'Vietnamese Dong (₫)', symbol: '₫' },
  { code: 'VUV', name: 'Vanuatu Vatu (VUV)', symbol: 'VUV' },
  { code: 'WST', name: 'Samoan Tala (WST)', symbol: 'WST' },
  { code: 'XAF', name: 'Central African CFA Franc (FCFA)', symbol: 'FCFA' },
  { code: 'XCD', name: 'East Caribbean Dollar (EC$)', symbol: 'EC$' },
  { code: 'XCG', name: 'Caribbean guilder (Cg.)', symbol: 'Cg.' },
  { code: 'XDR', name: 'Special Drawing Rights (XDR)', symbol: 'XDR' },
  { code: 'XOF', name: 'West African CFA Franc (F CFA)', symbol: 'F CFA' },
  { code: 'XPF', name: 'CFP Franc (CFPF)', symbol: 'CFPF' },
  { code: 'YER', name: 'Yemeni Rial (YER)', symbol: 'YER' },
  { code: 'ZAR', name: 'South African Rand (ZAR)', symbol: 'ZAR' },
  { code: 'ZMW', name: 'Zambian Kwacha (ZMW)', symbol: 'ZMW' },
  { code: 'ZWG', name: 'Zimbabwean Gold (ZWG)', symbol: 'ZWG' },
  { code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024) (ZWL)', symbol: 'ZWL' }
];

export function formatCurrency(value: unknown, currencyCode: string = 'INR') {
  const n = Number(value ?? 0);
  if (Number.isNaN(n)) return '0';
  
  try {
    return new Intl.NumberFormat(undefined, {
      style: 'currency',
      currency: currencyCode,
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(n);
  } catch (e) {
    const symbol = SUPPORTED_CURRENCIES.find(c => c.code === currencyCode)?.symbol || currencyCode;
    return `${symbol}${n.toFixed(2)}`;
  }
}
